// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hchjbzpczqrnoiocmnnw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhjaGpienBjenFybm9pb2Ntbm53Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNTA1MDAsImV4cCI6MjA2MzkyNjUwMH0.2I9tWqELCD0ocdWC_XLttBbRfr_eN0CDH7GKZQuCeCg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);